services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: gymdb
    ports:
      - "3306:3306"
  session:
    image: redis
    ports:
      - "6379:6379"
